const PluginData = [
  {
    pluginId: 1,
    icon: '/media/plugins/jstree/profileQuestions.jpg',
    name: 'Profile questions and Interest',
    type: 'Software',
    description: 'Customize your users profile with your own custom questions and interest system',
    status: 'Active',
    path: 'question_answer_plugin',
  },
  {
    pluginId: 2,
    icon: '/media/plugins/jstree/gifts.jpg',
    name: 'Gifts',
    type: 'Software',
    description: 'Allow users to send gift eachother',
    status: 'Active',
    path: 'gifts_plugin',
  },
  {
    pluginId: 3,
    icon: '/media/plugins/jstree/chat.jpg',
    name: 'Chat',
    type: 'Pages',
    description: 'Configure the messaging system',
    status: 'Active',
    path: 'chat_plugin',
  },
  {
    pluginId: 4,
    icon: '/media/plugins/jstree/rewards.jpg',
    name: 'Rewards',
    type: 'Software',
    description: 'Give free credits to users after complete some tasks in the site',
    status: 'Active',
    path: 'reward_plugin',
  },
  {
    pluginId: 5,
    icon: '/media/plugins/jstree/credits.jpg',
    name: 'Site pricing',
    type: 'Software',
    description: 'Update the credits and premium pricing details',
    status: 'Active',
    path: 'site_pricing_plugin',
  },
  {
    pluginId: 6,
    icon: '/media/plugins/jstree/populars.jpg',
    name: 'Populars',
    type: 'Pages',
    description: 'Shows the most populars users in the platform',
    status: 'Active',
    path: 'populars_plugin',
  },
  {
    pluginId: 7,
    icon: '/media/plugins/jstree/spotlight.jpg',
    name: 'Spotlight',
    type: 'Software',
    description: 'Allow users to get into the spotlight and get seen more by others',
    status: 'Active',
    path: 'spotlight_plugin',
  },
  {
    pluginId: 8,
    icon: '/media/plugins/jstree/videocall.jpg',
    name: 'Videochat',
    type: 'Software',
    description: 'Peer to peer videocalling',
    status: 'Active',
    path: 'videocall_plugin',
  },
  {
    pluginId: 9,
    icon: '/media/plugins/jstree/terms.jpg',
    name: 'Legal information',
    type: 'Pages',
    description: 'Edit your site terms of use, privacy policy and cookies',
    status: 'Active',
    path: 'legal_information_plugin',
  },
]

export default PluginData
